homeWork_02/ex3_ArithmeticOperations/Egor_Barilo/ArithmeticOperations

Egor_Barilo_HW2_Task3

---

homeWork_02/ex4_RandomNumberGenerator/Artemiy_Stankevich/RandomGeneratorDemo.java

Artemiy_Stankevich_Hw2_Task4_RandomGeneratorDemo_java

---

homeWork_02/ex2_Types/Egor_Barilo/Types

Egor_Barilo_HW2_Task2

---

homeWork_02/ex2_Types/SergeiKlimovich_hw2_task2/SergeiKlimovich_hw2_task2

I have done the second task of homework #2. Please, approve it.

Create  SergeiKlimovich_hw2_task2

---

homeWork_02/ex3_ArithmeticOperations/Artemiy_Stankevich/MathOperationsDemo.java

Artemiy_Stankevich_Hw2_Task3_MathOperationsDemo_java

---

homeWork_03/ex1_Dog/Artemiy_Stankevich/DogDemo.java

My homework about class and object Dog

Artemiy_Stankevich_Hw3_Task1_DogDemo_java

---

homeWork_02/ex2_Types/Tanya_Sorokina/in_study4.txt

Could you please review my homework.

Idid my second homework task2.

---

homeWork_02/ex4_RandomNumberGenerator/Tanya_Sorokina/RandomGeneratorDemo.java

Could you please review my homework.

I did my HW2 task4.

---

homeWork_02/ex3_ArithmeticOperations/Tanya_Sorokina/MathOperationsDemo.java

Could you plese review my homework.

I did my second homework task3.

---

homeWork_02/ex1_Variables/names.txt

Colleagues, please check the correctness of the assignment. Thanks!

completed homework 2 task 1

---

homeWork_02/ex3_ArithmeticOperations/MathOperationsDemo.java

Colleagues, please check the correctness of the assignment. Thanks!

completed homework 2 task 3

---

homeWork_02/ex4_RandomNumberGenerator/RandomGeneratorDemo.java

Colleagues, please check the correctness of the assignment. Thanks!

completed homework 2 task 4

---

homeWork_03/ex2_Human/Artemiy_Stankevich/Human.java
homeWork_03/ex2_Human/Artemiy_Stankevich/HumanDemo.java

I did my homework 3 Task 2 Human object

Artemiy_Stankevich_Hw3_Task2

---

homeWork_02/ex3_ArithmeticOperations/Sergei_Divokov/MathOperationsDemo

I did it, could you please review my work

MathOperationsDemo_t3

---

homeWork_03/ex3_Circle/Artemiy_Stankevich/Circle.java
homeWork_03/ex3_Circle/Artemiy_Stankevich/CircleDemo.java

Artemiy stankevich hw3 task3

---

homeWork_03/ex4_Encoder/Artemiy_Stankevich/Encoder.java
homeWork_03/ex4_Encoder/Artemiy_Stankevich/EncoderDemo.java

check out my homework about Encoder please

Artemiy stankevich hw3 task4

---

homeWork_03/ex5_Product/Artemiy_Stankevich/Product.java
homeWork_03/ex5_Product/Artemiy_Stankevich/ProductDemo.java

check out my hw3 task 5 please

Artemiy stankevich hw3 task5

---

homeWork_04/ex1_SignComparator/Artemiy_Stankevich/SignComparator.java
homeWork_04/ex1_SignComparator/Artemiy_Stankevich/SignComparatorTest.java
homeWork_04/ex1_SignComparator/Artemiy_Stankevich/SingComparatorService.java

Artemiy stankevich hw4 task1

---

homeWork_04/ex2_Phrase_Analyser/Artemiy_Stankevich/PhraseAnalyser.java
homeWork_04/ex2_Phrase_Analyser/Artemiy_Stankevich/PhraseAnalyserService.java
homeWork_04/ex2_Phrase_Analyser/Artemiy_Stankevich/PhraseAnalyserTest.java

Artemiy stankevich hw4 task2

---

homeWork_03/ex1_Dog/Dog.java
homeWork_03/ex1_Dog/DogDemo.java

Could you please review my HW3 task1.

I did my HW3 task1

---

homeWork_03/ex2_Human/Egor_Barilo/Human
homeWork_03/ex2_Human/Egor_Barilo/HumanDemo
homeWork_03/ex2_Human/Egor_Barilo/HumanService

Egor_Barilo_HW3_Task2

---

homeWork_03/ex2_Human/Human.java
homeWork_03/ex2_Human/HumanDemo.java

Could you please review my HW.

I did my HW!

---

homeWork_03/ex4_Encoder/Encoder.java
homeWork_03/ex4_Encoder/EncoderDemo.java

Could you please review my HW.

I did my HW3 task4.

---

homeWork_03/ex5_Product/Product.java
homeWork_03/ex5_Product/ProductDemo.java

I did my HW3 all!

---

homeWork_03/ex4_Encoder/Egor_Barilo/Encoder
homeWork_03/ex4_Encoder/Egor_Barilo/EncoderDemo
homeWork_03/ex4_Encoder/Egor_Barilo/EncoderService

Egor_Barilo_HW3_Task4

---

homeWork_04/ex1_SignComparator/SignComparator
homeWork_04/ex1_SignComparator/SignComparatorDemo
homeWork_04/ex1_SignComparator/SignComparatorService
homeWork_04/ex1_SignComparator/SignComparatorTest

Egor_Barilo_HW4_Task1

---

homeWork_04/ex3_ColorDetector/Artemiy_Stankevich/LightColorDetector.java
homeWork_04/ex3_ColorDetector/Artemiy_Stankevich/LightColorDetectorService.java
homeWork_04/ex3_ColorDetector/Artemiy_Stankevich/LightColorDetectorServiceTest.java

Artemiy stankevich hw4 task3
